# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.CharField(default='Snippet', max_length=500),
            preserve_default=False,
        ),
    ]
